DB_NAME = ''            #'your_db_name'
DB_USER = ''            #'your_db_user'
DB_PASS = ''            #'your_db_password'
DB_HOST = 'localhost'   #'your_db_host'
DB_PORT = ''            #'your_db_port'